### ISSUE TITLE
Feature parity with `std::collections::BTree{Set,Map}`

### ISSUE THREAD

**Issue by msrd0** [msrd0/aatree#15]
# [`BTreeMap`](https://doc.rust-lang.org/1.66.0/std/collections/struct.BTreeMap.html)

# Functions

 - [x] `append` (#20)
 - [x] `clear`
 - [x] `contains_key`
 - [ ] `drain_filter` <kbd>nightly</kbd>
 - [x] `entry` (#27)
 - [x] `first_entry` <kbd>1.66</kbd> (#27)
 - [x] `first_key_value` <kbd>1.66</kbd>
 - [x] `get`
 - [x] `get_key_value`
 - [x] `get_mut`
 - [x] `insert`
 - [x] `into_keys`
 - [x] `into_values`
 - [x] `is_empty`
 - [x] `iter`
 - [ ] `iter_mut`
 - [x] `keys`
 - [x] `last_entry` <kbd>1.66</kbd> (#27)
 - [x] `last_key_value` <kbd>1.66</kbd>
 - [x] `len`
 - [x] `new`
 - [ ] `new_in` <kbd>nightly</kbd>
 - [x] `pop_first` <kbd>1.66</kbd>
 - [x] `pop_last` <kbd>1.66</kbd>
 - [ ] `range`
 - [ ] `range_mut`
 - [x] `remove`
 - [x] `remove_entry`
 - [ ] `retain`
 - [ ] `split_off`
 - [ ] `try_insert` <kbd>nightly</kbd>
 - [x] `values`
 - [ ] `values_mut`

## Traits

 - [x] `Clone`
 - [x] `Debug`
 - [x] `Default`
 - [x] `Eq` (#19)
 - [x] `Extend<(&K, &V)>` (#18)
 - [x] `Extend<(K, V)>` (#18)
 - [x] `From<[(K, V); N]>` (#16)
 - [x] `FromIterator<(K, V)>`
 - [ ] `Hash`
 - [ ] `Index<&Q>`
 - [x] `IntoIterator for &Self`
 - [ ] `IntoIterator for &mut Self`
 - [x] `IntoIterator for Self`
 - [x] `Ord` (#19)
 - [x] `PartialEq` (#19)
 - [x] `PartialOrd` (#19)

# [`BTreeSet`](https://doc.rust-lang.org/1.66.0/std/collections/struct.BTreeSet.html)

## Functions

 - [x] `append` (#20)
 - [x] `clear` (#21)
 - [x] `contains`
 - [ ] `difference`
 - [ ] `drain_filter` <kbd>nightly</kbd>
 - [x] `first` <kbd>1.66</kbd>
 - [ ] `get`
 - [x] `insert`
 - [ ] `intersection`
 - [ ] `is_disjoint`
 - [x] `is_empty`
 - [ ] `is_subset`
 - [ ] `is_superset`
 - [x] `iter`
 - [x] `last` <kbd>1.66</kbd>
 - [x] `len`
 - [x] `new`
 - [ ] `new_in` <kbd>nightly</kbd>
 - [x] `pop_first` <kbd>1.66</kbd>
 - [x] `pop_last` <kbd>1.66</kbd>
 - [ ] `range`
 - [x] `remove`
 - [ ] `replace`
 - [ ] `retain`
 - [ ] `split_off`
 - [ ] `symmetric_difference`
 - [x] `take`
 - [ ] `union`

## Traits

 - [ ] `BitAnd`
 - [ ] `BitOr`
 - [ ] `BitXor`
 - [x] `Clone`
 - [x] `Debug`
 - [x] `Default`
 - [x] `Eq` (#19)
 - [x] `Extend<&T>` (#18)
 - [x] `Extend<T>` (#18)
 - [x] `From<[T; N]>` (#16)
 - [x] `FromIterator<T>`
 - [ ] `Hash`
 - [x] `IntoIterator for &Self`
 - [x] `IntoIterator for Self`
 - [x] `Ord` (#19)
 - [x] `PartialEq` (#19)
 - [x] `PartialOrd` (#19)
 - [ ] `Sub`

# [`Entry`](https://doc.rust-lang.org/1.66.0/std/collections/btree_map/enum.Entry.html)

## Functions

 - [x] `and_modify` (#27)
 - [x] `key` (#27)
 - [x] `or_default` (#27)
 - [x] `or_insert` (#27)
 - [x] `or_insert_with` (#27)
 - [x] `or_insert_with_key` (#27)

## Traits

 - [x] `Debug` (#27)

# [`OccupiedEntry`](https://doc.rust-lang.org/1.66.0/std/collections/btree_map/struct.OccupiedEntry.html)

## Functions

 - [x] `get` (#27)
 - [x] `get_mut` (#27)
 - [x] `insert` (#27)
 - [x] `into_mut` (#27)
 - [x] `key` (#27)
 - [ ] `remove`
 - [ ] `remove_entry`

## Traits

 - [x] `Debug` (#27)

# [`VacantEntry`](https://doc.rust-lang.org/1.66.0/std/collections/btree_map/struct.VacantEntry.html)

## Functions

 - [x] `insert` (#27)
 - [x] `into_key` (#27)
 - [x] `key` (#27)

## Traits

 - [x] `Debug` (#27)
